debug: False
overwrite: True
ndim: 3
run_id: anatomy_simple_500_epochs # Nome claro para a pasta de resultados
out_dir: output
model_dir: models
log_dir: logs
seed: 42
device: 'cuda'

# --- Configurações de Dados ---
data:
  data_dir: prostate158
  train_csv: prostate158/train.csv
  valid_csv: prostate158/valid.csv
  test_csv: prostate158/test.csv
  image_cols: t2
  label_cols: t2_anatomy_reader1
  dataset_type: persistent
  cache_dir: cache/monai_cache
  batch_size: 4

# --- Configurações de Transformações (usando as mesmas do seu baseline) ---
transforms:
  prob: 0.175
  spacing: [0.5, 0.5, 0.5]
  orientation: RAS
  rand_affine:
    rotate_range: 5
    shear_range: 0.5
    translate_range: 25
  rand_crop_pos_neg_label:
   spatial_size: [96, 96, 96]
   pos: 2
   neg: 1
   num_samples: 8

# --- Configurações do Modelo (UNet Original) ---
model:
  name: UNet
  out_channels: 3
  channels: [16, 32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2, 2]
  num_res_units: 4
  act: PRELU
  norm: BATCH
  dropout: 0.15

# --- Configurações do Otimizador ---
optimizer:
  Novograd:
    lr: 0.001

# --- Agendador de Taxa de Aprendizagem ---
lr_scheduler:
  OneCycleLR:
    max_lr: 0.001

# --- Função de Perda ---
loss:
  DiceCELoss:
    include_background: False
    softmax: True
    to_onehot_y: True

# --- Configurações de Treinamento ---
training:
  max_epochs: 500                 # <-- AUMENTADO PARA 500
  early_stopping_patience: 50 