debug: False
overwrite: False
ndim: 3
run_id: tumor_test_4 # Novo ID, nova esperança!
out_dir: output
model_dir: models
log_dir: logs
seed: 42
device: 'cuda'

data:
  data_dir: prostate158
  train_csv: prostate158/train.csv
  valid_csv: prostate158/valid.csv
  test_csv: prostate158/test.csv
  image_cols: [t2, adc, dwi]
  label_cols: adc_tumor_reader1
  train: True
  valid: True
  test: False
  # MUDANÇA FINAL: Ambas as chaves são necessárias.
  # dataset_type: standard -> para usar o dataset leve em memória.
  # cache_dir: ... -> para evitar o AttributeError, mesmo que não seja usado intensivamente.
  dataset_type: standard
  cache_dir: /tmp/monai-cache
  batch_size: 2

transforms:
  prob: 0.5
  spacing: [0.5, 0.5, 0.5]
  orientation: RAS
  rand_affine:
    rotate_range: 5
    shear_range: 0.5
    translate_range: 25
  rand_spatial_crop_samples:
     roi_size: [96, 96, 96]
     num_samples: 2 # Mantido baixo para evitar crash de memória
  shift_intensity:
    offsets: 0.1

model:
  out_channels: 2
  channels: [16, 32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2, 2]
  num_res_units: 4
  act: PRELU
  norm: BATCH
  dropout: 0.15

optimizer:
  Novograd:
    lr: 0.001
    weight_decay: 0.01
    amsgrad: True

lr_scheduler:
  OneCycleLR:
    max_lr: 0.001

loss:
  DiceFocalLoss:
    include_background: False
    softmax: True
    to_onehot_y: True

training:
  max_epochs: 10
  early_stopping_patience: 50